# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec78c7c0eef897def28493d66f89e3ed3cd3aaa0b2570a667d14a692b968e15df3856b706b5f7dfcc1612d18219ba7e1e40103315e3eaa0addb0b6c0f5f3eqw

test:
  secret_key_base: e3ba00ca9943677a92fabbd9926c231ecd0ee324268731225d92d8e3f761f320276510caf35d1833ffab39786c4d7e55561fa8727cc77d5d52e109a52b1b1148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
